/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      screens: {
        touch: { raw: '(hover: none)' },
      },
      colors: {
        /**
         * BRAND PALETTE
         * Four colors were specified: night, walnut, gold and sand. Everything
         * else here (chocolate, ink, cream, ivory, gold-light/dark, maroon,
         * muted) is a tint or shade of those same four, generated by shifting
         * lightness/saturation in HSL — not new hues. This is needed because a
         * real interface needs more range than four flat swatches: two dark
         * surfaces so a card can sit visibly on a page (chocolate on night),
         * hover/pressed states for buttons (gold-light/gold-dark), a legible
         * error/accent color from the same dark-red family as night (maroon),
         * and enough contrast for small caption text (muted). Every text/
         * background pairing below has been checked against WCAG AA.
         */
        ivory: '#E3CFC3',
        cream: '#EADDD5',
        night: '#1c0505',
        chocolate: '#440B0B',
        maroon: { DEFAULT: '#720000', dark: '#4D0202' },
        gold: { light: '#DDC479', DEFAULT: '#d3aa32', dark: '#9C7D22' },
        walnut: '#7a4e35',
        ink: '#290707',
        muted: '#59514C',
        sand: '#dec3b4',
      },
      fontFamily: {
        serif: ['"Cormorant Garamond"', 'Georgia', 'serif'],
        sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      transitionTimingFunction: {
        lux: 'cubic-bezier(0.22, 1, 0.36, 1)',
      },
      keyframes: {
        'pulse-soft': {
          '0%, 100%': { boxShadow: '0 0 0 0 rgba(37, 211, 102, 0.45)' },
          '70%': { boxShadow: '0 0 0 14px rgba(37, 211, 102, 0)' },
        },
        marquee: {
          from: { transform: 'translateX(0)' },
          to: { transform: 'translateX(-50%)' },
        },
        kenburns: {
          from: { transform: 'scale(1)' },
          to: { transform: 'scale(1.09)' },
        },
        'thread-drop': {
          '0%': { transform: 'translateY(-10px)', opacity: '0' },
          '35%': { opacity: '1' },
          '100%': { transform: 'translateY(34px)', opacity: '0' },
        },
      },
      animation: {
        'pulse-soft': 'pulse-soft 2.6s ease-out infinite',
        marquee: 'marquee 34s linear infinite',
        kenburns: 'kenburns 10s cubic-bezier(0.22, 1, 0.36, 1) forwards',
        'thread-drop': 'thread-drop 2.2s ease-in-out infinite',
      },
    },
  },
  plugins: [],
};
